---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: martinbjeldbak-com
spec:
  dnsNames:
    - martinbjeldbak.com
    - "*.martinbjeldbak.com"
  duration: 160h
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  secretName: martinbjeldbak-com-tls
  usages:
    - digital signature
