---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: go2rtc
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: go2rtc-secret
    template:
      data:
        GO2RTC_USERNAME: "{{ .GO2RTC_USERNAME }}"
        GO2RTC_PASSWORD: "{{ .GO2RTC_PASSWORD }}"
  dataFrom:
    - extract:
        key: go2rtc
